[versions]
agp = "9.0.0"
androidgitversion = "0.4.14"
commonmark = "0.17.0"
coreKtx = "1.17.0"
# espressoCore = "..."
hirondelleDate4j = "1.5.1"
junit = "4.13.2"
junitVersion = "1.3.0"
kotlin = "2.3.0"
kotlinStdlib = "2.3.0"
ksp = "2.3.2"
localbroadcastmanager = "1.1.0"
luajJse = "3.0.1"
material = "1.13.0"
preference = "1.2.1"
recyclerview = "1.4.0"
room = "2.8.4"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
# androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-localbroadcastmanager = { group = "androidx.localbroadcastmanager", name = "localbroadcastmanager", version.ref = "localbroadcastmanager" }
androidx-preference = { module = "androidx.preference:preference-ktx", name = "preference", version.ref = "preference" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
commonmark = { module = "com.atlassian.commonmark:commonmark", version.ref = "commonmark" }
hirondelle-date4j = { module = "com.darwinsys:hirondelle-date4j", version.ref = "hirondelleDate4j" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlinStdlib" }
luaj-jse = { module = "org.luaj:luaj-jse", version.ref = "luajJse" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
androidgitversion = { id = "com.gladed.androidgitversion", version.ref = "androidgitversion" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
